### ISSUE TITLE
Reduce image sizes (improve initial image load time)

### ISSUE THREAD

**Issue by wisdomekpotu** [MLH-Fellowship/prep-portfolio-22.AUG.PREP.2#38]
## Images take a lot of time to load initially
![slowimage](https://user-images.githubusercontent.com/58194343/182701352-242363cd-b8c0-4d86-b4fe-b41ffa508396.png)

**Comment by ahmedsaed** [comment]
I just wanted to let you know that I added a GitHub action in #19 that's supposed to compress images but it only works in some scenarios and to cover all scenarios I made it to run every Sunday to compress all images 

So it haven't compressed them yet but it should 

this is instead of doing it manually

**Comment by wisdomekpotu** [comment]
Okay, cool guess i should close this issue then
